### ISSUE TITLE
Option to use ajax if possible?

### ISSUE THREAD

**Issue by bikramchettri** [ryanwelcher/advanced-query-loop#11]
Can you add an option for adding ajax to the query block?

**Comment by ryanwelcher** [comment]
Hi there and thanks for opening this issue. Can you explain more in-depth what you are looking to have the block do? I'm not sure I understand the need to add AJAX when the block already handles the querying. Thanks!

**Comment by bikramchettri** [comment]
There should be an option to add ajax if the query has more than 10 posts without needing to change the query string. Currently, the page reloads if we want to visit another page.

**Comment by ryanwelcher** [comment]
Thanks for the clarification!

There is currently work being done to add [client-side navigation to the Query Loop block](https://github.com/WordPress/gutenberg/pull/53812). It is available with [Gutenberg 16.6](https://make.wordpress.org/core/2023/09/06/whats-new-in-gutenberg-16-6-06-september/) and I have tested it with AQL and it works great so I will wait until WordPress 6.4 comes out for this feature.
