### ISSUE TITLE
[Feature Request] Order by meta value (meta_value and meta_value_num)

### ISSUE THREAD

**Issue by richardtape** [ryanwelcher/advanced-query-loop#13]
Hi Ryan! Thanks so much for making this block!

It's been great to see it progress over the last few weeks. Really appreciate you putting this out there.

I'd like to start a conversation as to whether you'd like to see the ability for advanced query loops be ordered by the values for meta keys.

`WP_Query` allows the `orderby` param to take several values, two of which are `meta_value` and `meta_value_num`. These allow you to order the results of your query using the value of the meta key you're querying with. The latter allows you to order by numeric values, the former covers pretty much everything else.

Do you think AQL would benefit from a feature like this? If so, would you be willing to accept a PR for this (or would you rather work on this?).

**Comment by ryanwelcher** [comment]
Hi @richardtape and thanks for opening this!

I think any feature that will provide value is worth exploring and I'd be very open to a PR from you on this.

**Comment by ryanwelcher** [comment]
Just a follow-up here, I am working on this feature with the plans of having it out in the next release.

**Comment by richardtape** [comment]
Great to hear, Ryan.

For what it's worth, we ended up building something along these lines for the core Query Loop block. Feel free to take a look and see if you can take anything from there. We preferred using the native query loop block so folks didn't get confused between what was available in a Query Loop and an Advanced Query Loop.

https://repo.code.ubc.ca/ctlt-plugins/wp-query-block-extension-metadata-filter

We also built out the ability to sort by metadata: https://repo.code.ubc.ca/ctlt-plugins/wp-query-block-extension-metadata-sort

and we also added the ability to exclude posts within the core Query Loop Block: https://repo.code.ubc.ca/ctlt-plugins/wp-query-block-extension-exclude-posts

We're...let's say... light on documentation. But that will come.
