### ISSUE TITLE
How about ACF checkbox?

### ISSUE THREAD

**Issue by zoltanet** [ryanwelcher/advanced-query-loop#14]
So, I'm using your plugin to make some really cool stuff. :) I'm using it with acf fields, making query loops from custom post typtes. 

I'm having trouble with the checkbox field though. I have setup a checbkox in ACF and want to display some posts based on the selections. But it doesn't work. I've tried with the ACF Radio button - and it's working.

Post meta query: 
![image](https://user-images.githubusercontent.com/79929526/230063953-e7a99f63-4236-44aa-b6a8-0bbf34c0eda3.png)

I hope you understand what I mean :)

**Comment by ryanwelcher** [comment]
Thanks for opening this and sorry for my late response. I'd need to understand the set up a little better to be able to replace this. There are so many edge cases around working with post meta that it's going to be hard to fit them all into this UI.

**Comment by ryanwelcher** [comment]
This issue hasn't seen any response it's author. I'm going to close this out but feel free to open a new one with further information.
