### ISSUE TITLE
[feature suggestion] FIltering by Sticky statis for Custom Post Types

### ISSUE THREAD

**Issue by pedjas** [ryanwelcher/advanced-query-loop#18]
I have Custom Post Type News which is basically the same as Post but have soem additional Custom Taxonomy.

For some reason, by design, WordPress does not allow CustomPost to have Sticky enabled for Custom posts, but there is a plugin that allows that: Sticky Posts - Switch.

So now I have Custom Post Type Posts that are Sticky, but Query Loop does not support filtering by sticky state for Custom Post Types.

I hoped, your plugin, as it allows multiple post types in query would overcome this issue but no. Once I select custom Post Type, option to filter by sticky state is hidden.

Is it possible to add this option?

**Comment by ryanwelcher** [comment]
There are already controls in the standard Query Loop block that handle how sticky posts are treated.
