### ISSUE TITLE
Meta Key in the Post Meta Query not working if you are using ACF for creating custom fields

### ISSUE THREAD

**Issue by jvanja** [ryanwelcher/advanced-query-loop#27]
Hi Ryan again :)

As the title explains, if someone is using the ACF plugin and they try to enter an ACF field into the **Meta Key** input field (under the **Post Meta Query** section), it does not auto-complete and does not save the inputted field.

The fix is simple and I'll create a pull request in a bit.

Thanks for all your hard work!
-Vanja

**Comment by jessefriedman** [comment]
@jvanja I was able to get this working today with all the latest plugins.  If you type in the meta key and then press "enter" it locks it in.  It's the only way to get the custom ACF meta key to save. No matter what it won't auto fill but at least you can save it.
