### ISSUE TITLE
Show posts without showing sticky posts first

### ISSUE THREAD

**Issue by pedjas** [ryanwelcher/advanced-query-loop#37]
I use AQL to set custom selection of several post types at once. I noticed that regardless of query parameters I always get sticky posts first. For this very purpose i want sticky status to be ignored and posts displayed by specified sort order.

Moreover, as posts are listed as several pages, stocky posts show up in list on every page.

I cannot find setting to exclude sticky status form sort. Is that possible?

Another issue is that sticky posts are not counted in total number of displayed posts per page. I always end up with sticky posts displayed and then specified number of selected posts added. So I always have more posts and number of displayed posts changes depending on number of sticky posts. this ruins look of the site as posts are displayed in three columns and I always end up with some posts hanging on bottom of the page.

It would be great to have checkbox to just ignore sticky tag and treat all posts just as plain posts.

**Comment by ryanwelcher** [comment]
This is currently available in the Query Loop block that AQL extends.

You can set the Sticky Posts option to exclude:

![Cursor_and_Edit_Post_“AQL_Sticky_Posts”_‹_twitch-streams_—_WordPress](https://github.com/ryanwelcher/advanced-query-loop/assets/1259027/095efbd1-79f5-48b8-ae0c-7282b1117604)
