### ISSUE TITLE
Duplicated Blocks have the same ID

### ISSUE THREAD

**Issue by tedw4rd** [ryanwelcher/advanced-query-loop#42]
If I use the Duplicate function in the Block Editor to duplicate an AQL block, the resulting block always has the same ID as the original block. This can cause issues with pagination: if I have a page with two blocks that were created with this method, pressing the Next Page button on one block will cause _both_ blocks to advance to the next page. This happens even if you change the filters on one of them.

**Comment by ryanwelcher** [comment]
I tested this out quickly and it seems to be an issue with the Query Loop block itself. 

Unfortunatley, AQL is a block variation of the Query Loop block. so any issues it has AQL will also have. 

It looks like this is on the radar - https://github.com/WordPress/gutenberg/issues/55823
