### ISSUE TITLE
orderby meta_value -- meta_key not saving

### ISSUE THREAD

**Issue by silverhoopedge** [ryanwelcher/advanced-query-loop#44]
- when I typed in the string for the meta_key in the block sidebar, it did not save and the orderby meta_value did not produce expected results
- when I typed in the string for the meta_key **directly** into the code editor area, it did save and the orderby meta_value did produce expected results

(tested on a site with AQL plugin and TT4 theme only, regular posts, no category or tags)

**Comment by ryanwelcher** [comment]
Hi there and thanks for opening this issue. Would you be able to share a screencast of the steps to reproduce this issue?

There has been some issues around needing to press the Enter key after selecting or entering the meta_key field in the sidebar in order for it to persist.

**Comment by silverhoopedge** [comment]
Hi Ryan, thanks for the tip about the "enter key" - seems to be helping to resolve my confusing situation.

**Comment by ryanwelcher** [comment]
Perfect! I'm going to close this issue but feel free to open a new one if you run into issues again!
