### ISSUE TITLE
[Feature request] Show in list of blocks

### ISSUE THREAD

**Issue by matthew-dean** [ryanwelcher/advanced-query-loop#46]
Right now, the Advanced Query Loop does not show up in the list of blocks.

<img width="351" alt="Screenshot 2024-03-08 at 6 16 54 AM" src="https://github.com/ryanwelcher/advanced-query-loop/assets/414752/2c64a1cf-6b1b-4599-b159-b48426e15d58">

**Comment by ryanwelcher** [comment]
Hi! Can you confirm that the plugin is activated?

If it is, please let me know the the WordPress version and plugin version you are using so I can try to replicate this

**Comment by matthew-dean** [comment]
Sorry it was activated but for some reason it didn't show up right away, not sure why.
