### ISSUE TITLE
Not all public post types shown in additional post type dropdown

### ISSUE THREAD

**Issue by aaronware** [ryanwelcher/advanced-query-loop#51]
Not all publicly viewable Post types show in the additional post type dropdown. Using the latest version of the plugin and WordPress 6.4.3

Top Dropdown

![Screenshot by Dropbox Capture](https://github.com/ryanwelcher/advanced-query-loop/assets/3390827/afafd425-6ff6-4047-aea3-5a2ea4081f06)

Advanced Panel only showing 3?

![Screenshot by Dropbox Capture](https://github.com/ryanwelcher/advanced-query-loop/assets/3390827/795978ac-1db2-46a1-af4f-3ea4b6b55f27)

I see it's using the viewable filter. Strangely all these post types are public but I see some of them are not explicitly setting "publicly_queryable" and I wonder if that might have something to do with it?

**Comment by aaronware** [comment]
More posts are now visible in the list.

The core query loop block is enforcing hiding attachments, It may make sense to create another issue to define some common post types that should be hidden by default, or at least allow for the list to be filtered in the plugin.

For example this project uses Distributor however the dt_subscription post type really shouldn't be visible even though it technically is "visible"

![Screenshot by Dropbox Capture](https://github.com/ryanwelcher/advanced-query-loop/assets/3390827/07c0d0e8-e03d-46ea-a07c-7c4049f1dcd5)

**Comment by ryanwelcher** [comment]
This was addressed in 2.1.2 via #52
