### ISSUE TITLE
[Feature request] Order by comments / visualizations number

### ISSUE THREAD

**Issue by neoswf** [ryanwelcher/advanced-query-loop#57]
Hi there, this is an awesome plugin!
I would like to propose a new feature request: order a query by comments or visualization number.
Thank you!

**Comment by ryanwelcher** [comment]
Hi there! Can you clarify what you mean by "visualization number", please?

**Comment by ryanwelcher** [comment]
I've just released 3.0.0 that contains sorting by Comment Count. I've not heard back in regards to what you mean by visualization number" so I'll close this out as completed.

Please feel free to comment on this or open a new issue if needed.

Closed by #59 

Thanks!
