### ISSUE TITLE
Saving a post while ACF is quering for single posts breaks the page

### ISSUE THREAD

**Issue by vfede** [ryanwelcher/advanced-query-loop#67]
I use Kadence theme with pro addon.

I reproduce this bug everytime i create an AQL element and try to manually select a couple of posts to be shown.

>  [proxy_fcgi:error [pid 1361:tid 140577433614080 [client privateip:0 AH01071: Got error 'PHP message: PHP Fatal error: Uncaught TypeError: Return value of AdvancedQueryLoop\\Query_Params_Generator::get_custom_............ntent/plugins/advanced-query-loop/includes/query-loop.php(65): AdvancedQueryLoop\\Query_Params_Generator->process_all()\n#4 /home/949052.cloudwaysapps.com/kjskbmbydw/public_...', referer: https://redacted.com/wp-admin/edit.php?post_type=page

I can't seem to be able to recover the post, i need to go to db and copy the contents and create a new one. Pretty critical.

These are my active plugins.
![image](https://github.com/ryanwelcher/advanced-query-loop/assets/1517314/c9afb099-a823-4823-a289-1b8cdf5d057e)

**Comment by ryanwelcher** [comment]
Thanks for reporting. I have seen similar issue and have a fix ready to be released.

**Comment by ryanwelcher** [comment]
I've just released 3.0.1 that should address this. Can you update and test it please?

**Comment by ryanwelcher** [comment]
Similar issue have been fixed with the last release. I'm going to close this out as fixed but please let me know if any other issue arise.
