### ISSUE TITLE
How to change <ul> and <li> to <div> in the generated HTML?

### ISSUE THREAD

**Issue by vivi-gomez** [ryanwelcher/advanced-query-loop#80]
Hi!. First, thank you for this great project! it's been really helpful.

 I have a specific requirement where I need to modify the HTML structure generated by the block. Right now, the block is wrapping the post items inside a `<ul>` with each post as an `<li>`. For my project, I would prefer if the structure was generated using only `<div>` elements instead of `<div><ul><li><figure>`  and `<img>`.
I tried to add an Additional CSS class(es) .Grid-mosaico and in the Post template .Grid-mosaico-item. However, I unable to get the css working as I would like.
This is an example of what I get from the block

```
<div class="entry-content wp-block-post-content is-layout-constrained wp-block-post-content-is-layout-constrained">
	<div class="wp-block-query Grid-mosaico is-layout-flow wp-block-query-is-layout-flow">
		<ul class="Grid-mosaico-item wp-block-post-template is-layout-flow wp-block-post-template-is-layout-flow">
			<li class="wp-block-post post-509 post type-post status-publish format-standard has-post-thumbnail hentry category-grid_general">
				<figure class="wp-block-post-featured-image">
				<img ....
               </figure>
            </li>
        </ul>
    </div>
</div>
```
I've tried looking through the codebase, but I couldn't find where the ul and li elements are being generated. Could you point me to the right place in the code where these elements are created? Or, if there's a recommended way to customize this output, I would greatly appreciate your guidance.

Thank you in advance for your help!

**Comment by ryanwelcher** [comment]
Hi there and thanks for using AQL!

This is actually not possible via the plugin as it doesn't manage the output of the Post Template blocks. You would need to create some custom blocks and use those as the template or potentially modify the output of the blocks using the `render_block` filter.

I'm going to close this out because it's not actionable here but if you run into issues, please feel free to open a new issue!
